### ISSUE TITLE
limit((x**(x + 1)*(ln(x) + 1) + 1)/x, x, 11) uses too much memory

### ISSUE THREAD

**Issue by skirpichev** [diofant/diofant#1155]
E.g. with ulimit -v == 512Mb:
```
$ DIOFANT_GROUND_TYPES=python python -m diofant --no-ipython 
>>> limit((x**(x + 1)*(ln(x) + 1) + 1)/x, x, 11)
Traceback (most recent call last):
...
  File "/home/sk/src/diofant/diofant/core/expr.py", line 162, in __pow__
    return Pow(self, other)
  File "/home/sk/src/diofant/diofant/core/cache.py", line 56, in wrapper
    return cfunc(*args, **kwargs)
  File "/home/sk/src/diofant/diofant/core/power.py", line 211, in __new__
    obj = b._eval_power(e)
  File "/home/sk/src/diofant/diofant/core/numbers.py", line 1301, in _eval_power
    result = Integer(x**abs(expt.numerator))
MemoryError
```
The minimal x0 value seems to be 8:
```
>>> limit((x**(x + 1)*(ln(x) + 1) + 1)/x, x, 1)
2
>>> limit((x**(x + 1)*(ln(x) + 1) + 1)/x, x, 2)
4⋅log(2) + 9/2
>>> limit((x**(x + 1)*(ln(x) + 1) + 1)/x, x, 3)
82/3 + 27⋅log(3)
>>> limit((x**(x + 1)*(ln(x) + 1) + 1)/x, x, 4)
1025/4 + 512⋅log(2)
>>> limit((x**(x + 1)*(ln(x) + 1) + 1)/x, x, 5)
15626/5 + 3125⋅log(5)
>>> limit((x**(x + 1)*(ln(x) + 1) + 1)/x, x, 6)
279937/6 + 46656⋅log(6)
>>> limit((x**(x + 1)*(ln(x) + 1) + 1)/x, x, 7)
5764802/7 + 823543⋅log(7)
>>> limit((x**(x + 1)*(ln(x) + 1) + 1)/x, x, 8)
134217729/8 + 50331648⋅log(2)
```

For the gmpy ground type it crashes the python interpreter:
```
$ python -m diofant --no-ipython 
>>> limit((x**(x + 1)*(ln(x) + 1) + 1)/x, x, 9)
GNU MP: Cannot allocate memory (size=9606088)
Aborted
```
(It crashes also without limits with error "gmp: overflow in mpz type".)

See also https://github.com/sympy/sympy/issues/21661

**Comment by skirpichev** [comment]
One problem is sympy/sympy/issues/19813.  E.g. ``logcombine(Rational(3138428376722, 11) + 285311670611*log(11))``.
