### ISSUE TITLE
[regression in 0.14.0] TypeError: the first argument must be callable

### ISSUE THREAD

**Issue by yurivict** [diofant/diofant#1334]
```import diofant``` fails:
```
Traceback (most recent call last):
  File "/usr/ports/math/py-Diofant/x.py", line 1, in <module>
    import diofant
  File "/usr/local/lib/python3.9/site-packages/diofant/__init__.py", line 6, in <module>
    from .calculus import Limit, O, Order, limit, maximize, minimize, residue
  File "/usr/local/lib/python3.9/site-packages/diofant/calculus/__init__.py", line 5, in <module>
    from .limits import Limit, limit
  File "/usr/local/lib/python3.9/site-packages/diofant/calculus/limits.py", line 1, in <module>
    from ..core import (Add, Dummy, Expr, Float, PoleError, Rational, nan, oo,
  File "/usr/local/lib/python3.9/site-packages/diofant/core/__init__.py", line 7, in <module>
    from .expr import Expr, AtomicExpr
  File "/usr/local/lib/python3.9/site-packages/diofant/core/expr.py", line 3164, in <module>
    from .power import Pow  # noqa: E402
  File "/usr/local/lib/python3.9/site-packages/diofant/core/power.py", line 18, in <module>
    from .symbol import Dummy, symbols
  File "/usr/local/lib/python3.9/site-packages/diofant/core/symbol.py", line 14, in <module>
    class BaseSymbol(AtomicExpr, Boolean):
  File "/usr/local/lib/python3.9/site-packages/diofant/core/symbol.py", line 137, in BaseSymbol
    __xnew_cached_ = cacheit(__new_stage2__)  # symbols are always cached
  File "/usr/local/lib/python3.9/site-packages/diofant/core/cache.py", line 48, in cacheit
    cfunc = functools.lru_cache(maxsize=maxsize, typed=True)(f)
  File "/usr/local/lib/python3.9/functools.py", line 518, in decorating_function
    wrapper = _lru_cache_wrapper(user_function, maxsize, typed, _CacheInfo)
TypeError: the first argument must be callable
```

0.13.0 didn't have such problem.

Python-3.9
FreeBSD 13.2

**Comment by skirpichev** [comment]
Please note, that 0.14.0 doesn't support CPython 3.9, see e.g.:
https://diofant.readthedocs.io/en/latest/release/notes-0.14.html#compatibility-breaks
or
https://pypi.org/project/Diofant/0.14.0/
