### ISSUE TITLE
0.15.0: TypeError: cannot create mpf from Decimal('Infinity')

### ISSUE THREAD

**Issue by yurivict** [diofant/diofant#1444]
There is a regression in 0.15.0 compared to 0.14.0:
```
$ python3.11
Python 3.11.10 (main, Oct 10 2024, 01:05:52) [Clang 18.1.5 (https://github.com/llvm/llvm-project.git llvmorg-18.1.5-0-g617a15 on freebsd14
Type "help", "copyright", "credits" or "license" for more information.
>>> import diofant
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/diofant/__init__.py", line 6, in <module>
    from .calculus import Limit, O, Order, limit, maximize, minimize, residue
  File "/usr/local/lib/python3.11/site-packages/diofant/calculus/__init__.py", line 5, in <module>
    from .limits import Limit, limit
  File "/usr/local/lib/python3.11/site-packages/diofant/calculus/limits.py", line 4, in <module>
    from ..sets import Reals
  File "/usr/local/lib/python3.11/site-packages/diofant/sets/__init__.py", line 14, in <module>
    Reals = S.Reals
            ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/diofant/core/singleton.py", line 76, in __getattr__
    value_to_install = class_to_install()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/diofant/core/singleton.py", line 136, in __call__
    cls.__class__._instances[cls] = super().__call__(*args, **kwargs)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/diofant/sets/fancysets.py", line 220, in __new__
    return super().__new__(cls, left_open=True, right_open=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/diofant/sets/sets.py", line 736, in __new__
    if (end - start).is_negative:
        ~~~~^~~~~~~
  File "/usr/local/lib/python3.11/site-packages/diofant/core/decorators.py", line 78, in __sympifyit_wrapper
    return func(a, b)
           ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/diofant/core/numbers.py", line 1534, in __sub__
    if other in (oo, nan, Float('inf')):
                          ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/diofant/core/numbers.py", line 490, in __new__
    _mpf_ = mpmath.mpf(num, prec=prec, rounding=rnd)._mpf_
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mpmath/ctx_mp_python.py", line 79, in __new__
    v._mpf_ = mpf_pos(cls.mpf_convert_arg(val, prec, rounding), prec, rounding)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mpmath/ctx_mp_python.py", line 98, in mpf_convert_arg
    raise TypeError("cannot create mpf from " + repr(x))
TypeError: cannot create mpf from Decimal('Infinity')
```

Python-3.11
FreeBSD 14.1

**Comment by skirpichev** [comment]
Works for me:
```
sk@note:~ $ python3.11 -m venv xxx
sk@note:~ $ . ~/xxx/bin/activate
(xxx) sk@note:~ $ pip install diofant
Collecting diofant
  Downloading Diofant-0.15.0-py3-none-any.whl.metadata (4.0 kB)
Collecting mpmath>=1.4.0a1 (from diofant)
  Downloading mpmath-1.4.0a2-py3-none-any.whl.metadata (9.2 kB)
Downloading Diofant-0.15.0-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 4.6 MB/s eta 0:00:00
Downloading mpmath-1.4.0a2-py3-none-any.whl (558 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 558.8/558.8 kB 3.0 MB/s eta 0:00:00
Installing collected packages: mpmath, diofant
Successfully installed diofant-0.15.0 mpmath-1.4.0a2

[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
(xxx) sk@note:~ $ python
Python 3.11.9+ (heads/3.11:795f2597a4, Aug 29 2024, 14:29:51) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import diofant
>>> diofant.sin(1)
sin(1)
```

Which version of the mpmath you are using?

**Comment by yurivict** [comment]
py311-mpmath-1.3.0_1

**Comment by skirpichev** [comment]
The v0.15 requires mpmath>=1.4.0a1:
https://github.com/diofant/diofant/blob/b39ae680fd5a445c39cfd500084b8a750073e44b/pyproject.toml#L28
